name: kiratakip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path: ^1.9.0
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.3.2
  flutter_speed_dial: ^7.0.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  circle_nav_bar: ^2.1.0+1
  get: ^4.6.6
  iconsax: ^0.0.8
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/hotel.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/hotel.png
    - assets/resimler/birinci.png
    - assets/resimler/ikinci.png
    - assets/resimler/dorduncu.png
    - assets/resimler/ucuncu.png
